Fix delete metadata update
akkadotnet/Akka.Persistence.PostgreSql pull request #72
Opened 2020-03-19 19:47 UTC by annymsMthd

Signed-off-by: Joshua Benjamin <joshuabnjmn@gmail.com>

2020-03-19 19:48 UTC, annymsMthd commented
Npgsql doesn't like multiple commands in the delete for some reason.

2020-03-25 11:13 UTC, CumpsD commented
Thanks @annymsMthd

2020-11-11 22:02 UTC, Aaronontheweb commented
crap, I need to update the CI system for this plugin, don't I?

2020-11-11 23:45 UTC, CumpsD commented
and all other PRs ;)

2021-03-05 18:11 UTC, Arkatufus commented
@CumpsD Can you resolve the merge conflict?

2021-03-05 20:30 UTC, Arkatufus commented
@annymsMthd Can you resolve the merge conflict?

2021-03-05 20:40 UTC, Arkatufus requested changes
Looks good, just needed a few tweaks.

2021-03-05 20:40 UTC, Arkatufus commented on src/Akka.Persistence.PostgreSql/Journal/PostgreSqlQueryExecutor.cs
> +        public string DeleteBatchSqlMetadata { get; }
This property should be made protected.

2021-03-05 20:40 UTC, Arkatufus commented on src/Akka.Persistence.PostgreSql/Journal/PostgreSqlQueryExecutor.cs
> +            DeleteBatchSqlMetadata = $@"
Can you add a comment here, explaining why we need to separate the SQL script into two?

2021-03-12 19:40 UTC, closed without merging

2021-03-16 15:38 UTC, CumpsD commented on src/Akka.Persistence.PostgreSql/Journal/PostgreSqlQueryExecutor.cs
> +        public string DeleteBatchSqlMetadata { get; }
Or private?